version: '3.7'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3.6
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_USER=anil
      - CLICKHOUSE_PASSWORD=senocak
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1  # Enables RBAC
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP interface
      - "9009:9009"   # Internal TCP communication
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    networks:
      - boilerplate
volumes:
  couchbase_data:
networks:
  boilerplate: